version: '3.9'

services:
  db:
    image: postgres:alpine
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=p2p_army
  cache:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    # command: redis-server --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

volumes:
  db:
  cache:
